modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="frazers_mod"
version="1.0.0"
displayName="Frazer's Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/SirenGlitch/Minecraft_Java_Mod"
authors="Frazer"
description='''
I made this for fun.
'''

[[dependencies.frazers_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




